version: '3.8'

services:

  node-app:
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - mern-app


  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:data/db
    networks:
      - mern-app


networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
